version: "3"

services:
  3-5-2-server:
    volumes:
    - .:/app # this will enable changes made to the server JS to reflect in the container
    build: .
    ports:
      - "3000:3000"
    networks:
      - 3-5-2-network

  3-5-2-db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: 3-5-2
      MYSQL_ROOT_PASSWORD: JHkj%^a8832:!
    volumes:
      - dbdata:/var/lib/mysql
      - "./scripts/mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - 3-5-2-network

#Volumes
volumes:
  dbdata:
    driver: local

#Docker Networks
networks:
  3-5-2-network:
    driver: bridge