version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-resources-352"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3tgcpcpoy8rn"
s3_prefix = "sam-resources-352"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "NotificationEmail=\"whitej031788@gmail.com\""
